import { readFile } from 'node:fs/promises';
const manifest=JSON.parse(await readFile('index/knowledge-manifest.json','utf8'));
const cfg=JSON.parse(await readFile('config/retrieval-ranking.json','utf8'));
const staleCfg=JSON.parse(await readFile('config/staleness-policy.json','utf8'));
const norm=s=>String(s??'').toLowerCase();
const tokenise=s=>new Set(norm(s).split(/[^a-z0-9_\-]+/).filter(x=>x.length>1));
async function body(e){try{return await readFile(e.path,'utf8');}catch{return '';}}
function freshness(e,now){const hs=(e.domains??[]).map(d=>staleCfg.domainMaxAgeDays[d]).filter(Number.isFinite);const h=hs.length?Math.min(...hs):staleCfg.defaultMaxAgeDays;if(!e.lastVerifiedAt)return {unverified:true,stale:false};return {unverified:false,stale:(now-new Date(e.lastVerifiedAt))/86400000>h};}
export async function retrieve({project='',domains=[],keywords=[],query='',now=new Date(),mode='hybrid',limit=10}){const qTokens=tokenise([query,...keywords,...domains,project].join(' '));const scored=[];for(const e of manifest.entries){if(['rejected','superseded','subsumed'].includes(e.status))continue;let metadata=0;metadata+=cfg.weights.type[e.type]??0;metadata+=cfg.weights.status[e.status]??0;if(project&&(e.projects??[]).some(p=>norm(p)===norm(project)))metadata+=cfg.weights.projectExact;for(const d of domains)if((e.domains??[]).some(x=>norm(x)===norm(d)))metadata+=cfg.weights.domainExactEach;if((e.projects??[]).length>1)metadata+=cfg.weights.multiProject;if((e.evidenceIds??[]).length)metadata+=cfg.weights.hasEvidence;const f=freshness(e,now);metadata+=f.unverified?cfg.weights.unverified:cfg.weights.verified;if(f.stale)metadata+=cfg.weights.stalePenalty;const text=await body(e);const hayTokens=tokenise([e.id,e.path,...(e.domains??[]),...(e.projects??[]),text].join(' '));let hits=0;for(const t of qTokens)if(hayTokens.has(t))hits++;const lexical=qTokens.size?hits/qTokens.size:0;const score=mode==='metadata'?metadata:mode==='fulltext'?lexical*100:metadata+lexical*35;scored.push({id:e.id,type:e.type,status:e.status,path:e.path,score:Number(score.toFixed(3)),metadataScore:metadata,lexicalScore:Number(lexical.toFixed(3))});}return scored.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,limit);}
